package ubc.cosc322;

import java.util.ArrayList;
import static java.util.Arrays.asList;
import java.util.Collections;
import java.util.PriorityQueue;

public class ArtificialMoveTree {
    ArtificialPlayer player;
    int max_depth = 1;

    ArrayList<MoveNode> parents = new ArrayList<>(); //this stores the parents of the leaf nodes to make minimax sorting easier
    MoveNode current;
    public ArtificialMoveTree(ArtificialPlayer player){
        this.player=player;
        current = new MoveNode(null,this.player,null,0);
        this.expandDepth(current,0);
    }

    public void expandDepth(MoveNode root, int count){
        if(count==this.max_depth){
            return;
        }
        root.generateChildrenInitial();
        if(count==this.max_depth-1){
            this.parents.add(root);
        }
        for(MoveNode child: root.children){
            this.expandDepth(child, count+1);
        }
    }

    //gets the best immediate next move based on depth search
    //returns an arraylist of arraylists containing the 3 arraylists corresponding to move syntax
    MoveNode getNextMoveNode(){
        PriorityQueue<MoveNode> parent_comp=new PriorityQueue<>();
        if(this.is_max()){
            parent_comp=new PriorityQueue<>(Collections.reverseOrder());
        }

        for(MoveNode m: this.parents){
            if(!m.children.isEmpty()){
                parent_comp.add(m.children.peek());
            } else if (m.move != null) {
                parent_comp.add(m);
            }
        }

        if (parent_comp.isEmpty()) {
            System.out.println("[WARN] Minimax parents list is empty; falling back to depth-1 best child.");
            return findNonReversal(this.current.children);
        }

        // Prefer the best-scoring move; fall back to next-best if it would
        // exactly undo the last move we played (avoids infinite oscillation).
        MoveNode best = findImmediateNode(parent_comp.peek());
        if (!isReversal(best)) {
            return best;
        }
        // Best is a reversal: scan all children of every parent for an alternative.
        for (MoveNode p : this.parents) {
            // Copy preserves the PQ's comparator (MAX or MIN ordering).
            PriorityQueue<MoveNode> childCopy = new PriorityQueue<>(p.children);
            while (!childCopy.isEmpty()) {
                MoveNode candidate = findImmediateNode(childCopy.poll());
                if (candidate != null && !isReversal(candidate)) return candidate;
            }
        }
        return best; // Every option is a reversal; accept and move anyway.
    }

    /**
     * Returns true when playing {@code node} would move a queen back to where
     * it came from on the previous turn (per-queen history).
     *
     * Tracks each queen independently, so interleaved moves by different queens
     * are correctly handled (e.g. queen A oscillates even when queen B moved
     * in between the two A-moves).
     */
    private boolean isReversal(MoveNode node) {
        if (node == null || node.move == null) return false;
        ArrayList<Integer> from = node.move.get(0);
        ArrayList<Integer> to   = node.move.get(1);
        // Look up where the queen currently at `to` came from on our last move.
        ArrayList<Integer> prevPos = player.queenPrevPos.get(to.toString());
        return prevPos != null && prevPos.equals(from);
    }

    /** Scans a PQ (copied, not mutated) for the best-scoring non-reversal node. */
    private MoveNode findNonReversal(PriorityQueue<MoveNode> source) {
        if (source == null || source.isEmpty()) return null;
        PriorityQueue<MoveNode> copy = new PriorityQueue<>(source);
        MoveNode fallback = copy.peek();
        while (!copy.isEmpty()) {
            MoveNode candidate = copy.poll();
            if (!isReversal(candidate)) return candidate;
        }
        return fallback; // All were reversals; return best anyway.
    }
    ArrayList<ArrayList<Integer>> getNextMove(){
        MoveNode node = this.getNextMoveNode();
        if (node == null) {
            System.out.println("[ERROR] getNextMoveNode() returned null — no legal moves found.");
            return null;
        }
        return node.move;
    }
    boolean is_max(){ //determines if we need to take the max of the min children (true) or min of the max children (false)
        // Odd max_depth means the leaf layer was generated by the opponent (minimizer),
        // so we want to pick the parent whose best leaf is the maximum score.
        return this.max_depth % 2 != 0;
    }
    void progressMove(){
        //applies a move to traverse the tree
        //the children nodes need to be updated to the next max_depth

        //updates the current pointer node to be the actual game state
        for(MoveNode m: this.current.children){
            if(this.player.gameBoard.equals(m.gameState)){
                this.current = m;
                break;
            }
        }

        this.pruneTree();

        ArrayList<MoveNode> new_parents = new ArrayList<>();
        for(MoveNode m: this.parents){
            for(MoveNode mn: m.children){
                mn.generateChildren();
                if(mn.children.isEmpty()){
                    new_parents.add(mn.parent);
                }else{
                new_parents.add(mn);}
            }
        }
        this.parents=new_parents;
    }
    void pruneTree(){
        //cleans up the tree to avoid generating for dead nodes that cannot be achieved
        ArrayList<MoveNode> new_parents = new ArrayList<>();
        for(MoveNode m: this.parents){
            if(findImmediateNode(m).parent.equals(this.current)){
                new_parents.add(m);
            }
        }
        this.parents=new_parents;
    }

    MoveNode findImmediateNode(MoveNode ideal_node){
        //traverse up the ideal future game state's tree to find the immediate next move
        if(ideal_node==null){
            return null;
        }
        MoveNode next_node = ideal_node;
        while(true){
            ideal_node=ideal_node.parent;
            if(ideal_node == null){
                // Traversed past root without finding current; broken tree state.
                return null;
            }
            if(ideal_node.equals(this.current)){
                break;
            }
            next_node=next_node.parent;
        }
        return next_node;
    }
}

class MoveNode implements Comparable<MoveNode>{
    PriorityQueue<MoveNode> children = new PriorityQueue<>();
    ArrayList<Integer> gameState = new ArrayList<>();
    MoveNode parent;
    int value;
    int max_depth;
    ArrayList<ArrayList<Integer>> move;
    HeuristicEvaluator eval;
    ArtificialPlayer player;
    public MoveNode(MoveNode parent, ArtificialPlayer player, ArrayList<ArrayList<Integer>> associatedMove, int depth){
        this.move=associatedMove;
        this.player=player;
        this.max_depth = depth;
        this.eval = this.player.heuristicEvaluator;
        this.parent=parent;

        //make a fake gameboard for evaluation, then store this movenode's gamestate

        ArrayList<Integer> fake_board = new ArrayList<>();
        if(parent!=null){
            fake_board = new ArrayList<>(parent.gameState);
        }else{
            fake_board = new ArrayList<>(player.gameBoard);
        }
        if(associatedMove!=null){
            player.heuristicEvaluator.applyMove(fake_board,associatedMove.get(0),associatedMove.get(1),associatedMove.get(2));
        }
        this.gameState=new ArrayList<>(fake_board);
        this.value = player.heuristicEvaluator.evaluate(fake_board,player.myPlayerCode);

        // Even depth = our turn (maximizer) → children ordered descending (MAX).
        // Odd depth  = opponent's turn (minimizer) → default ascending (MIN).
        if(this.max_depth % 2 == 0){
            children = new PriorityQueue<>(Collections.reverseOrder());
        }
    }
    public void generateChildren(){
        // Even depth = our turn (myPlayerCode); odd depth = opponent's turn.
        int myCode = this.player.myPlayerCode;
        int oppCode = (myCode == 1) ? 2 : 1;
        int color = (this.max_depth % 2 == 0) ? myCode : oppCode;
        for(int i = 1; i<11; i++){
            for(int j = 1; j < 11; j++){
                if(this.eval.getCell(this.gameState,i,j)==color){
                    ArrayList<ArrayList<Integer>> moves = this.eval.generateValidMoves(this.gameState,new ArrayList<>(asList(i,j)));
                    for(ArrayList<Integer> to: moves){

                        ArrayList<Integer> fake_board = new ArrayList<>(this.gameState);
                        this.eval.setCell(fake_board,i,j,0);
                        ArrayList<ArrayList<Integer>> arrows = this.eval.generateValidMoves(fake_board,to);

                        ArrayList<Integer> from = new ArrayList<>(asList(i,j));

                        for(ArrayList<Integer> arrow: arrows){
                            MoveNode mn = new MoveNode(this,this.player, new ArrayList<>(asList(from, to, arrow)), max_depth);
                            this.children.add(mn);
                        }

                    }
                }
            }
        }
    }
    public void generateChildrenInitial(){
        // Even depth = our turn (myPlayerCode); odd depth = opponent's turn.
        int myCode = this.player.myPlayerCode;
        int oppCode = (myCode == 1) ? 2 : 1;
        int color = (this.max_depth % 2 == 0) ? myCode : oppCode;
        for(int i = 1; i<11; i++){
            for(int j = 1; j < 11; j++){
                if(this.eval.getCell(this.gameState,i,j)==color){
                    ArrayList<ArrayList<Integer>> moves = this.eval.generateValidMoves(this.gameState,new ArrayList<>(asList(i,j)));
                    for(ArrayList<Integer> to: moves){

                        ArrayList<Integer> fake_board = new ArrayList<>(this.gameState);
                        this.eval.setCell(fake_board,i,j,0);
                        ArrayList<ArrayList<Integer>> arrows = this.eval.generateValidMoves(fake_board,to);

                        ArrayList<Integer> from = new ArrayList<>(asList(i,j));

                        for(ArrayList<Integer> arrow: arrows){
                            MoveNode mn = new MoveNode(this,this.player, new ArrayList<>(asList(from, to, arrow)), max_depth+1);
                            this.children.add(mn);
                        }

                    }
                }
            }
        }
    }
    @Override
    public int compareTo(MoveNode o) {
        return this.value-o.value;
    }
}