package ubc.cosc322;

import java.util.ArrayDeque;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Deque;

/**
 * Heuristic evaluator and board utility methods for the Game of the Amazons.
 *
 * Design goals:
 * 1) Keep AI-specific logic outside ArtificialPlayer for cleaner separation.
 * 2) Provide reusable helpers for move generation and board updates.
 * 3) Offer a deterministic evaluation function for search algorithms.
 *
 * Board model assumptions (aligned with the ygraph framework):
 * - The board is a flattened 11x11 integer array-list.
 * - Valid game squares use row/col in [1..10].
 * - Cell encoding:
 *   0 = empty
 *   1 = black queen
 *   2 = white queen
 *   3 = arrow / blocked square
 */
public class HeuristicEvaluator {

    private static final int BOARD_DIM = 11;
    private static final int BOARD_MIN = 1;
    private static final int BOARD_MAX = 10;

    private static final int EMPTY = 0;
    private static final int BLACK_QUEEN = 1;
    private static final int WHITE_QUEEN = 2;
    private static final int ARROW = 3;

    private static final int[][] DIRS = new int[][]{
            {-1, -1}, {-1, 0}, {-1, 1},
            {0, -1},           {0, 1},
            {1, -1},  {1, 0},  {1, 1}
    };

    /**
     * Generates all legal queen-like moves from a position on the current board.
     *
     * A move is generated by extending a ray in each of the 8 directions until
     * a non-empty cell or board boundary is reached.
     *
     * @param boardState current flattened board state
     * @param pos source coordinate [row, col]
     * @return list of reachable [row, col] targets
     */
    public ArrayList<ArrayList<Integer>> generateValidMoves(ArrayList<Integer> boardState, ArrayList<Integer> pos) {
        ArrayList<ArrayList<Integer>> moves = new ArrayList<>();
        if (boardState == null || pos == null || pos.size() < 2) {
            return moves;
        }

        int row = pos.get(0);
        int col = pos.get(1);
        for (int[] dir : DIRS) {
            int r = row + dir[0];
            int c = col + dir[1];
            while (isInside(r, c) && getCell(boardState, r, c) == EMPTY) {
                ArrayList<Integer> next = new ArrayList<>(2);
                next.add(r);
                next.add(c);
                moves.add(next);
                r += dir[0];
                c += dir[1];
            }
        }
        return moves;
    }

    /**
     * Applies a move (queen movement + arrow shot) to a board state in place.
     *
     * Operation order:
     * 1) Clear queen source square.
     * 2) Place queen on destination square.
     * 3) Mark arrow square as blocked.
     *
     * @param boardState mutable flattened board state
     * @param from queen source [row, col]
     * @param to queen destination [row, col]
     * @param arrow arrow target [row, col]
     */
    public void applyMove(ArrayList<Integer> boardState, ArrayList<Integer> from,
                          ArrayList<Integer> to, ArrayList<Integer> arrow) {
        if (boardState == null || from == null || to == null || arrow == null) {
            return;
        }
        if (from.size() < 2 || to.size() < 2 || arrow.size() < 2) {
            return;
        }

        int fromR = from.get(0), fromC = from.get(1);
        int toR = to.get(0), toC = to.get(1);
        int arrowR = arrow.get(0), arrowC = arrow.get(1);
        if (!isInside(fromR, fromC) || !isInside(toR, toC) || !isInside(arrowR, arrowC)) {
            return;
        }

        int movingPiece = getCell(boardState, fromR, fromC);
        setCell(boardState, fromR, fromC, EMPTY);
        setCell(boardState, toR, toC, movingPiece);
        setCell(boardState, arrowR, arrowC, ARROW);
    }

    /**
     * Evaluates a board from the perspective of playerCode.
     * Positive score means better for playerCode.
     *
     * Heuristic composition:
     * - Mobility term: difference in total legal queen moves.
     * - Territory term: difference in square control based on shortest queen-move
     *   distance from each side to each empty square.
     *
     * Score = 2 * (selfMobility - oppMobility) + 5 * territoryScore
     *
     * @param boardState current flattened board state
     * @param playerCode side to evaluate for (1=black, 2=white)
     * @return signed heuristic score
     */
    public int evaluate(ArrayList<Integer> boardState, int playerCode) {
        if (boardState == null || boardState.size() < BOARD_DIM * BOARD_DIM) {
            return 0;
        }

        int otherCode = (playerCode == BLACK_QUEEN) ? WHITE_QUEEN : BLACK_QUEEN;
        int mobilitySelf = countMobility(boardState, playerCode);
        int mobilityOpp = countMobility(boardState, otherCode);

        int[] distSelf = computeQueenDistanceMap(boardState, playerCode);
        int[] distOpp = computeQueenDistanceMap(boardState, otherCode);
        int territoryScore = computeTerritoryScore(distSelf, distOpp);

        int mobilityWeight = 2;
        int territoryWeight = 5;
        return mobilityWeight * (mobilitySelf - mobilityOpp) + territoryWeight * territoryScore;
    }

    /**
     * Counts total legal queen destinations over all queens of a side.
     */
    private int countMobility(ArrayList<Integer> boardState, int playerCode) {
        int total = 0;
        for (int r = BOARD_MIN; r <= BOARD_MAX; r++) {
            for (int c = BOARD_MIN; c <= BOARD_MAX; c++) {
                if (getCell(boardState, r, c) == playerCode) {
                    total += countMovesFrom(boardState, r, c);
                }
            }
        }
        return total;
    }

    /**
     * Counts all queen-like ray moves from one square.
     */
    private int countMovesFrom(ArrayList<Integer> boardState, int row, int col) {
        int count = 0;
        for (int[] dir : DIRS) {
            int r = row + dir[0];
            int c = col + dir[1];
            while (isInside(r, c) && getCell(boardState, r, c) == EMPTY) {
                count++;
                r += dir[0];
                c += dir[1];
            }
        }
        return count;
    }

    /**
     * Computes minimum number of queen moves from any queen of playerCode to
     * every reachable empty square.
     *
     * This is a BFS over "queen move graph":
     * - Each node is an empty square.
     * - An edge exists if one queen move can reach the other square.
     *
     * Distance 0 is assigned to squares currently occupied by the side's queens.
     * Unreachable squares remain Integer.MAX_VALUE.
     */
    private int[] computeQueenDistanceMap(ArrayList<Integer> boardState, int playerCode) {
        int[] dist = new int[BOARD_DIM * BOARD_DIM];
        Arrays.fill(dist, Integer.MAX_VALUE);
        Deque<int[]> queue = new ArrayDeque<>();

        for (int r = BOARD_MIN; r <= BOARD_MAX; r++) {
            for (int c = BOARD_MIN; c <= BOARD_MAX; c++) {
                if (getCell(boardState, r, c) == playerCode) {
                    int idx = toIndex(r, c);
                    dist[idx] = 0;
                    queue.offer(new int[]{r, c});
                }
            }
        }

        while (!queue.isEmpty()) {
            int[] current = queue.poll();
            int row = current[0];
            int col = current[1];
            int baseDist = dist[toIndex(row, col)];
            for (int[] dir : DIRS) {
                int r = row + dir[0];
                int c = col + dir[1];
                while (isInside(r, c) && getCell(boardState, r, c) == EMPTY) {
                    int idx = toIndex(r, c);
                    if (dist[idx] > baseDist + 1) {
                        dist[idx] = baseDist + 1;
                        queue.offer(new int[]{r, c});
                    }
                    r += dir[0];
                    c += dir[1];
                }
            }
        }
        return dist;
    }

    /**
     * Converts two distance maps into a territory differential score.
     *
     * For each board square:
     * - +1 if only self can reach it, or self reaches it faster.
     * - -1 if only opponent can reach it, or opponent reaches it faster.
     * - 0 on ties / mutually unreachable squares.
     */
    private int computeTerritoryScore(int[] distSelf, int[] distOpp) {
        int score = 0;
        for (int r = BOARD_MIN; r <= BOARD_MAX; r++) {
            for (int c = BOARD_MIN; c <= BOARD_MAX; c++) {
                int idx = toIndex(r, c);
                boolean selfReach = distSelf[idx] != Integer.MAX_VALUE;
                boolean oppReach = distOpp[idx] != Integer.MAX_VALUE;
                if (selfReach && !oppReach) {
                    score++;
                } else if (!selfReach && oppReach) {
                    score--;
                } else if (selfReach && distSelf[idx] < distOpp[idx]) {
                    score++;
                } else if (oppReach && distSelf[idx] > distOpp[idx]) {
                    score--;
                }
            }
        }
        return score;
    }

    /**
     * Reads a cell by converting 2D board coordinates into flattened index.
     */
    private int getCell(ArrayList<Integer> boardState, int row, int col) {
        return boardState.get(toIndex(row, col));
    }

    /**
     * Writes a cell by converting 2D board coordinates into flattened index.
     */
    private void setCell(ArrayList<Integer> boardState, int row, int col, int value) {
        boardState.set(toIndex(row, col), value);
    }

    /**
     * Converts [row, col] to the framework's 1D layout index.
     */
    private int toIndex(int row, int col) {
        return BOARD_DIM * row + col;
    }

    /**
     * Returns true if the coordinate lies in the playable 10x10 region.
     */
    private boolean isInside(int row, int col) {
        return row >= BOARD_MIN && row <= BOARD_MAX && col >= BOARD_MIN && col <= BOARD_MAX;
    }
}
